### ISSUE TITLE
About the use of CelebAMask-HQ dataset

### ISSUE THREAD

**Issue by Samaritan-Infi** [eladrich/pixel2style2pixel#148]
```
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./datasets/inference_dataset.py", line 21, in __getitem__
    from_im = self.transform(from_im)
  File "/usr/local/lib64/python3.6/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "./datasets/augmentations.py", line 27, in __call__
    one_hot = self.onehot_initialization(img)
  File "./datasets/augmentations.py", line 17, in onehot_initialization
    out[self.__all_idx(a, axis=2)] = 1
IndexError: index 87 is out of bounds for axis 2 with size 1
```

I use the below bash to inference 
```
python3 scripts/inference.py \
--exp_dir=/apdcephfs/private_feiiyin/psp \
--checkpoint_path=/apdcephfs/private_feiiyin/psp/pretrained_models/psp_celebs_seg_to_face.pt \
--data_path=/apdcephfs/share_1016399/feiiyin/data/CelebAMask-HQ/ \
--test_batch_size=1 \
--test_workers=4 \
--couple_outputs \
--n_images=9 \
--latent_mask=8,9,10,11,12,13,14,15,16,17
```

The directory structure of `/apdcephfs/share_1016399/feiiyin/data/CelebAMask-HQ/ ` is as follows:
```
total 5709
drwxr-xr-x  2 root root 2762671560 May 31 15:22 CelebA-HQ-img
-rw-r--r--  1 root root     990032 Apr 25  2019 CelebA-HQ-to-CelebA-mapping.txt
-rw-r--r--  1 root root    3622218 Apr  3  2019 CelebAMask-HQ-attribute-anno.txt
drwxr-xr-x 17 root root  576688716 May 31 18:05 CelebAMask-HQ-mask-anno
-rw-r--r--  1 root root    1230055 Apr  3  2019 CelebAMask-HQ-pose-anno.txt
-rw-------  1 root root       1896 May 13  2019 README.txt
```

Is the dataset I downloaded wrong? Thanks!

**Comment by yuval-alaluf** [comment]
I think you downloaded the right dataset. Your data path is simply incorrect. Rather than providing the root to the directory you specified above, you should specify the path to the directory containing the masks themselves. Perhaps this is the subdirectory `CelebAMask-HQ-mask-anno` although I am not entirely sure.

**Comment by Samaritan-Infi** [comment]
I found it not work when set the subdirectory of `CelebAMask-HQ-mask-anno`.
The data in `CelebAMask-HQ-mask-anno` is the mask of different component e.g. eyes, which is not the same as the example image you provided.
When you train a mask encoder for psp, do you do other pre-handle on CelebAMask dataset, like combining the component together? 
Thanks for your reply.

**Comment by yuval-alaluf** [comment]
Our data was downloaded and processed using the following repo: 
https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing
There you should find additional preprocessing scripts. I believe this is the part you're missing.

**Comment by Samaritan-Infi** [comment]
Thanks, solved! 
Impressed by your excellent work!
