### ISSUE TITLE
How to get W+ space for the encoded images ?

### ISSUE THREAD

**Issue by 7khalil** [eladrich/pixel2style2pixel#15]
I tried running inference on a set of images for encoding in the FFHQ latent space, it gave me a set of projected images. But no .npy file associated with it for W+ space as cited in the paper to do further image maniputations.

Is it possible to get the W+ space vectors ?

**Comment by eladrich** [comment]
Hi @7khalil, please see the explanation in issue #11

**Comment by 7khalil** [comment]
Hi @eladrich, I followed the modification that needs to make in https://github.com/eladrich/pixel2style2pixel/blob/master/models/psp.py#L66 by setting return_latents=True. 
But when I tried to make inference, I got this error : 

Loading pSp from checkpoint: ./experiment/ckpt/psp_ffhq_encode.pt
Loading dataset for ffhq_encode
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2680, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 1, 256), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/inference.py", line 136, in <module>
    run()
  File "scripts/inference.py", line 82, in run
    result = tensor2im(result_batch[i])
  File "./utils/common.py", line 23, in tensor2im
    return Image.fromarray(var.astype('uint8'))
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2682, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 1, 256), |u1

is there another modification that needs to be done in the code, to retrive W+ ?

**Comment by yuval-alaluf** [comment]
Hi @7khalil ,
It's a bit hard to tell what the issue is without looking at the modification you made. Any chance you can send a snippet of the modification(s) you made in `inference.py`?  
In the meantime, please verify that `result_batch[i]` is the correct shape (probably something like (3, 256, 256)).

**Comment by eladrich** [comment]
Closing due to inactivity
