### ISSUE TITLE
use psp for stylegan-ada generator trained with only one channel

### ISSUE THREAD

**Issue by Mo-Irene** [eladrich/pixel2style2pixel#263]
Hi,  first of all, thank you very much for your excellent work. I had some problems when I was using it, I would really appreciate if you could give me some advice or help.

I'm using the stylegan2-ada generator trained with my own dataset, but my dataset is based on single channel images and when I try to use it with --stylegan_weights I get the following error:

```
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 27, in main
    coach = Coach(opts)
  File "./training/coach.py", line 36, in __init__
    self.net = pSp(self.opts).to(self.device)
  File "./models/psp.py", line 34, in __init__
    self.load_weights()
  File "./models/psp.py", line 63, in load_weights
    self.decoder.load_state_dict(ckpt['g_ema'], strict=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1070, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
	size mismatch for to_rgb1.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgb1.conv.weight: copying a param with shape torch.Size([1, 1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
	size mismatch for to_rgbs.0.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.0.conv.weight: copying a param with shape torch.Size([1, 1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
	size mismatch for to_rgbs.1.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.1.conv.weight: copying a param with shape torch.Size([1, 1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
	size mismatch for to_rgbs.2.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.2.conv.weight: copying a param with shape torch.Size([1, 1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
	size mismatch for to_rgbs.3.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
	size mismatch for to_rgbs.4.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 128, 1, 1]).
	size mismatch for to_rgbs.5.bias: copying a param with shape torch.Size([1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
	size mismatch for to_rgbs.5.conv.weight: copying a param with shape torch.Size([1, 1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 64, 1, 1]).

```
I guess it has something to do with my decoder channels, maybe it's set to default 3 channels ? So what can I do to make my psp network work correctly?

**Comment by yuval-alaluf** [comment]
It seems like the rosinality StyleGAN Generator code uses `3` channels by default: 
https://github.com/eladrich/pixel2style2pixel/blob/334f45e43335e92822744849a546c82e1cc47bb3/models/stylegan2/model.py#L347-L348
It seems like if you change these hard-coded `3` to `1`, it should match the parameter dimensions.

**Comment by Mo-Irene** [comment]
Thank you so much for such a quick reply!

After trying your suggestion, it looks like it's progressing, but there's still something wrong：

```
./training/coach.py:216: UserWarning: Using a target size (torch.Size([2, 3, 256, 256])) that is different to the input size (torch.Size([2, 1, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss_l2 = F.mse_loss(y_hat, y)
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 28, in main
    coach.train()
  File "./training/coach.py", line 92, in train
    loss, loss_dict, id_logs = self.calc_loss(x, y, y_hat, latent)
  File "./training/coach.py", line 236, in calc_loss
    loss_moco, sim_improvement, id_logs = self.moco_loss(y_hat, y, x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./criteria/moco_loss.py", line 51, in forward
    y_hat_feats = self.extract_feats(y_hat)
  File "./criteria/moco_loss.py", line 42, in extract_feats
    x_feats = self.model(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 393, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 389, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 1, 224, 224] to have 3 channels, but got 1 channels instead

```
Maybe there is something else in the code that I need to modify?

**Comment by yuval-alaluf** [comment]
What parameters are you running with? Did you make sure to change `input_nc` and `label_nc` to be equal to `1`?

**Comment by Mo-Irene** [comment]
I'm sorry I forgot to set input_nc to 1, I don't have a label input so I keep label_nc to 0, after adding this setting I get a new error, which seems to be related to my pretrained generator:
```
{'batch_size': 2,
 'board_interval': 50,
 'checkpoint_path': None,
 'dataset_type': 'my_data_encode',
 'encoder_type': 'GradualStyleEncoder',
 'exp_dir': './training-runs/test-op',
 'id_lambda': 0.0,
 'image_interval': 100,
 'input_nc': 1,
 'l2_lambda': 1.0,
 'l2_lambda_crop': 0,
 'label_nc': 0,
 'learn_in_w': False,
 'learning_rate': 0.0001,
 'lpips_lambda': 0.2,
 'lpips_lambda_crop': 0,
 'max_steps': 5000,
 'moco_lambda': 0.5,
 'optim_name': 'ranger',
 'output_size': 256,
 'resize_factors': None,
 'save_interval': 50,
 'start_from_latent_avg': True,
 'stylegan_weights': 'pretrained_models/network-snapshot-009800.pt',
 'test_batch_size': 2,
 'test_workers': 8,
 'train_decoder': False,
 'use_wandb': False,
 'val_interval': 25,
 'w_norm_lambda': 0,
 'workers': 8}
Loading encoders weights from irse50!
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 27, in main
    coach = Coach(opts)
  File "./training/coach.py", line 36, in __init__
    self.net = pSp(self.opts).to(self.device)
  File "./models/psp.py", line 34, in __init__
    self.load_weights()
  File "./models/psp.py", line 60, in load_weights
    self.encoder.load_state_dict(encoder_ckpt, strict=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1070, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GradualStyleEncoder:
	size mismatch for input_layer.0.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
```

**Comment by yuval-alaluf** [comment]
If you look, you're getting the following error: 
```
RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[2, 3, 256, 256] to have 1 channels, but got 3 channels instead
```
You defined a layer `self.input_layer(x)` that is supposed to get a single channel input, which is correct. But for some reason, it could `x` which was 3 channels instead. Therefore there is something in your input that is not correct. Did you run this in debug and make sure that `x` is the correct dimension before passing it to the encoder. That is, did make sure the images are processed correctly in the dataset? 
A lot of these adjustments are small things that should be easy to capture if you run in debug.

**Comment by Mo-Irene** [comment]
Thanks for answering patiently, I'll try to run it in debug, have a nice day:)
