### ISSUE TITLE
cuda illegal memory access was encountered 

### ISSUE THREAD

**Issue by huanhuanxuxu** [eladrich/pixel2style2pixel#51]
Hi, 
I've got an illegal memory access error, I'm training the "segmentation" tasks with batch size 2, CUDA 11.0:

Traceback (most recent call last):
  File "scripts/train.py", line 31, in <module>
    main()
  File "scripts/train.py", line 27, in main
    coach.train()
  File "./training/coach.py", line 78, in train
    y_hat, latent = self.net.forward(x, return_latents=True)
  File "./models/psp.py", line 93, in forward
    return_latents=return_latents)
  File "/home/huan/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./models/stylegan2/model.py", line 544, in forward
    skip = to_rgb(out, latent[:, i + 2], skip)
  File "/home/huan/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./models/stylegan2/model.py", line 357, in forward
    out = out + skip
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by huanhuanxuxu** [comment]
problem solved with using only "cuda:0" device instead of "cuda:1"
