### ISSUE TITLE
RuntimeError: psp_ffhq_toonify.pt is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by cumtwb** [eladrich/pixel2style2pixel#7]
environments:
python 3.6.7
torch 1.3.1     
torchvision  0.4.2 
CUDA 10.1
------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ightq\x04ct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/root/anaconda3/envs/psp_env/lib/python3.6/tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/inference.py", line 131, in <module>
    run()
  File "scripts/inference.py", line 43, in run
    ckpt = torch.load(test_opts.checkpoint_path, map_location='cpu')
  File "/root/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: psp_ffhq_toonify.pt is a zip archive (did you mean to use torch.jit.load()?)

**Comment by yuval-alaluf** [comment]
Hi, 
Can you please try upgrading the torch version to `torch==1.6.0` and let me know if this solves the problem.

**Comment by yuval-alaluf** [comment]
Can you provide more information? What script are you running?

**Comment by cumtwb** [comment]
I am running the commad as follows:
`python3 scripts/inference.py --exp_dir=outputs --checkpoint_path=psp_ffhq_toonify1.pt --data_path=input_data --test_batch_size=1 --test_workers=1 --couple_outputs`

**Comment by cumtwb** [comment]
This is the full log: 
`                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
/root/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py:172: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Loading pSp from checkpoint: psp_ffhq_toonify1.pt
Loading dataset for ffhq_encode
  0%|                                                                                 | 0/3 [00:00<?, ?it/s]
Segmentation fault`

**Comment by yuval-alaluf** [comment]
You may need to update your gcc. If it helps, I have gcc and g++ versions of 7.5.0.

**Comment by eladrich** [comment]
Closing due to inactivity.
